# Generated by Django 4.2.7 on 2026-01-23 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0.0)),
                ('avg_pressure', models.FloatField(default=0.0)),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('pump', 'Pump'), ('compressor', 'Compressor'), ('reactor', 'Reactor'), ('heat_exchanger', 'Heat Exchanger'), ('separator', 'Separator'), ('mixer', 'Mixer'), ('boiler', 'Boiler'), ('filter', 'Filter'), ('other', 'Other')], max_length=50)),
                ('flowrate', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='equipment.dataupload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment_type'], name='equipment_e_equipme_ce5345_idx'), models.Index(fields=['upload'], name='equipment_e_upload__ebb158_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['user', 'uploaded_at'], name='equipment_d_user_id_1ca0b9_idx'),
        ),
    ]
